changed yml to get apk

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -46,13 +46,20 @@ jobs:
       - name: Build APK with EAS
         working-directory: ${{ github.workspace }}/StickerSmash
         run: |
-          eas build --platform android --profile production --non-interactive
+          BUILD_OUTPUT=$(eas build --platform android --profile production --non-interactive)
+          echo "$BUILD_OUTPUT"
+          APK_URL=$(echo "$BUILD_OUTPUT" | grep -oP 'https://expo.dev/artifacts/eas/[\w-]+\.apk')
+          if [ -z "$APK_URL" ]; then
+            echo "Error: No APK URL found!" >&2
+            exit 1
+          fi
+          echo "APK_URL=$APK_URL" >> $GITHUB_ENV
 
       # Stap 8: Run Maestro Cloud Test
       - name: Run Maestro Cloud Test
         uses: mobile-dev-inc/action-maestro-cloud@v1.1.0
         with:
           api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
-          app-file: ${{ github.workspace }}/StickerSmash/build/app-debug.apk # Pas dit pad aan als nodig
+          app-file: ${{ env.APK_URL }}
           flow-file: .maestro/exploreTest.yaml
           async: true
